### PR TITLE
fix catkin_lint errors and all but one warning (#21)

### PR DESCRIPTION
**Pull request by jack-oquin**
Some of the catkin_lint errors were substantive, others just good practice.
I did not fix the "link_directories()" warning, not sure what to do about it.
Also fixed some but not all notices, mostly alphabetizing lists of things.

@PatrickHussey: Let's review this before merging.

### CODE REVIEW

**Comment by jack-oquin** [comment]
xref: #21

**Comment by jack-oquin** [comment]
This looks OK to me, and passes my tests, which exercise the base, but not much else.

**Comment by jack-oquin** [comment]
@PatrickHussey: would you be interested in running Travis CI on pull requests to this repository? It's free for open-source github repositories.

**Comment by jack-oquin** [comment]
The ``rosdep`` dependencies all resolve cleanly on Indigo with Ubuntu Trusty.

**Comment by jack-oquin** [comment]
Patrick: Any chance of merging this soon?

**Comment by PatrickHussey** [comment]
Sorry I out the last 2 weeks, should be merged and all set

**Comment by jack-oquin** [comment]
Thanks, @PatrickHussey! 

It was no problem for me. I just wanted to update the branches of our local fork, which we no longer need, but plan to keep around for possible future contributions.

**Pull request merged**
